
# example netlify.toml
[build]
  command = "npx pnpm install -r --store=node_modules/.pnpm-store && npx vite build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--version"
